services:
  prestashop.module.category_products.grid.definition.factory:
    class: 'JeremieP\PJCategoryProducts\CategoryProductsGridDefinitionFactory'
    arguments:
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.feature.multistore'
      - '@prestashop.adapter.shop.context'
      - '@form.factory'
      - '@PrestaShop\PrestaShop\Core\Grid\Action\Row\AccessibilityChecker\ProductSingleShopAssociatedAccessibilityChecker'
      - '@PrestaShop\PrestaShop\Core\Grid\Action\Row\AccessibilityChecker\ProductMultipleShopsAssociatedAccessibilityChecker'
      - '@translator'
    tags: ['prestashop.core.grid.definition.factory']

  prestashop.module.category_products.grid.query_builder:
    class: 'JeremieP\PJCategoryProducts\CategoryProductsQueryBuilder'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
      - '@prestashop.adapter.legacy.configuration'
      - '@PrestaShop\PrestaShop\Adapter\Shop\Repository\ShopGroupRepository'

  prestashop.module.category_products.grid.data.factory:
    class: 'JeremieP\PJCategoryProducts\CategoryProductsGridDataFactory'
    arguments:
      - '@prestashop.core.grid.data.factory.product'
      - '@prestashop.core.localization.locale.repository'

  prestashop.core.grid.factory.category_products:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@prestashop.module.category_products.grid.definition.factory'
      - '@prestashop.module.category_products.grid.data.factory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
    public: true

  prestashop.core.grid.accessibility_checker.single_shop:
    class: 'PrestaShop\PrestaShop\Core\Grid\Action\Row\AccessibilityChecker\SingleShopAccessibilityChecker'
    arguments:
      - '@prestashop.adapter.feature.multistore'

  prestashop.core.grid.accessibility_checker.multiple_shops:
    class: 'PrestaShop\PrestaShop\Core\Grid\Action\Row\AccessibilityChecker\MultipleShopsAccessibilityChecker'
    arguments:
      - '@prestashop.adapter.feature.multistore'